version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "python"
    assignees:
      - "piotr-rarus"
    groups:
      batch-version-updates:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      batch-security-updates:
        applies-to: security-updates
        update-types:
          - "minor"
          - "patch"
